### ISSUE TITLE
Service not being created on workspace deployment

### ISSUE THREAD

**Issue by swgriffith** [Azure/kaito#335]
When testing with an image that I pulled into my own Azure Container Registry from the supported MCR images for Kaito the pod comes online fine and is functional, however the kubernetes service is never created.

1. Pull an image for Kaito into your own ACR:
az acr import --name kaitodemo --source  mcr.microsoft.com/aks/kaito/kaito-mistral-7b-instruct:0.0.4 --image mistral-7b-instruct:0.0.4

2. Deploy a manifest with custom image source:

```yaml
apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-mistral-7b
resource:
  instanceType: "Standard_NC64as_T4_v3"
  labelSelector:
    matchLabels:
      apps: mistral-7b
inference:
  template:
    spec:
      containers:
      - name: mistral-7b-instruct-container
        image: kaitodemo.azurecr.io/mistral-7b-instruct:0.0.4
        command: ["accelerate"]
        args: ["launch", "--num_processes", "1", "--num_machines", "1", "--gpu_ids", "all", "text-gen-inference.py", "--pipeline", "text-generation", "--torch_dtype", "bfloat16"]
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory

``` 

3. Watch for creation of the deployment and service

**Expected Result**
Pods and service all created successfully

**Environment**

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.5", GitCommit:"9cf543f4f17cbc5b74c24880e77590eeb1af683c", GitTreeState:"clean", BuildDate:"2024-01-31T09:07:34Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
