### ISSUE TITLE
inference-frontend CrashLoopBackOff due to readiness and liveness prob fail

### ISSUE THREAD

**Issue by RoyKimYYZ** [Azure/kaito#658]
**Describe the bug**

Readiness and Liveness Prob fails
in the inference-frontend-5788c88b6b-r5m8p.1803160e23c6f863 pod, there is CrashLoopBackOff.

the event logs show
[Readiness probe failed:]
[Liveness probe failed:]

As a workaround to fix, I simply remove the readiness and liveness probe configuration in the deployment.yaml file from line 52. 

**Steps To Reproduce**

helm install inference-frontend ./charts/DemoUI/inference --set env.workspaceServiceURL="http://workspace-falcon-7b.default.svc.cluster.local:80/chat"

such that

~kaito/charts/DemoUI/inference/values.yaml have

...
livenessProbe:
  exec:
    command:
      - pgrep
      - chainlit
readinessProbe:
  exec:
    command:
      - pgrep
      - chainlit

**Expected behavior**

Fully running pod

**Logs**

**Environment**

AKS 1.29.9
Kaito v0.3.1
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Install tools:
- Others:

**Additional context**

**Comment by zhuangqh** [comment]
The problem lies in the time cost of pip install. please enlarge the timeout for liveness.
eg.
```
        livenessProbe:
          exec:
            command:
            - pgrep
            - chainlit
          failureThreshold: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
